### ISSUE TITLE
What data types it is not supported in schema-graphql-bridge?

### ISSUE THREAD

**Issue by veeramarni** [loredanacirstea/meteor-apollo-react-boilerplate#1]
This package seems to be very useful. In the read me you have mentioned it was only supported some limited data types. Can you also provide the data types it don't support?

**Comment by loredanacirstea** [comment]
Moved package to: https://github.com/kuip/meteor-schema-graphql-bridge
It is also published on Atmosphere now.

For our question see https://github.com/kuip/meteor-schema-graphql-bridge#simple-schema-types-supported
